FROM node:22-alpine

WORKDIR /app

COPY signaling-server/package.json signaling-server/package-lock.json* ./

RUN npm ci --omit=dev

COPY signaling-server/server.js .

EXPOSE 7333

CMD ["node", "server.js"]
