# fly.toml app configuration file generated for smartid2-signaling on 2026-05-04T07:55:57+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'smartid2-signaling'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 7333
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
